# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSUQo5SHkeej0GYhAknY4yTji8udMPwS
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Judul
st.title("Dashboard Analisis Data Mahasiswa")

# Load data
@st.cache_data
def load_data():
    data = pd.read_csv("data_mahasiswa_1000.csv")
    return data

data = load_data()

# Sidebar
st.sidebar.title("Navigasi")
page = st.sidebar.selectbox("Pilih Halaman", ["Informasi Data", "Visualisasi", "Statistik Deskriptif"])

# Halaman 1: Informasi Data
if page == "Informasi Data":
    st.subheader("Dataset Mahasiswa")
    st.write(data.head())
    st.write("Jumlah baris dan kolom:", data.shape)
    st.write("Kolom yang tersedia:", data.columns.tolist())

# Halaman 2: Visualisasi
elif page == "Visualisasi":
    st.subheader("Visualisasi Data")
    selected_col = st.selectbox("Pilih Kolom Kategori", data.select_dtypes(include=['object', 'category']).columns)

    fig, ax = plt.subplots()
    sns.countplot(x=selected_col, data=data, ax=ax)
    plt.xticks(rotation=45)
    st.pyplot(fig)

# Halaman 3: Statistik Deskriptif
elif page == "Statistik Deskriptif":
    st.subheader("Statistik Deskriptif")
    st.write(data.describe(include='all'))

    st.markdown("### Korelasi Numerik")
    num_data = data.select_dtypes(include=['int64', 'float64'])
    corr = num_data.corr()
    fig, ax = plt.subplots()
    sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax)
    st.pyplot(fig)